% Hechos
video_exp(aburrido, 'Aburrido_erirmw').
video_exp(actitud, 'Actitud_lqcatc').
video_exp(alegre, 'Alegre_ebch0i').
video_exp(amable, 'Amable_c0bmix').
video_exp(ansioso, 'Ansioso_wbj4fn').
video_exp(autoestima, 'Autoestima_ihubwd').
video_exp(cansado, 'Cansado_zj47dh').
video_exp(carinoso, 'Carinoso_qoqos1').
video_exp(creido, 'Creido_apetp3').
video_exp(deprimido, 'Deprimido_kaxse1').
video_exp(dolor, 'Dolor_ckymmy').
video_exp(egoista, 'Egoista_iv3hkg').
video_exp(emocion, 'Emocion_ct1qbi').
video_exp(enamorado, 'Enamorado_rphtfq').
video_exp(enojado, 'Enojado_nxqoul').
video_exp(envidia, 'Envidia_v22jh1').
video_exp(expresion, 'Expresion_jq3ice').
video_exp(feliz, 'Feliz_lfhtuw').
video_exp(frustrado, 'Frustrado_jqeuci').
video_exp(hambriento, 'Hambriento_r7d7w1').
video_exp(humilde, 'Humilde_r7kvff').
video_exp(injusto, 'Injusto_qjld7z').
video_exp(llorar, 'Llorar_xkviep').
video_exp(miedoso, 'Miedoso_kvzvcz').
video_exp(odiar, 'Odiar_dfpurt').
video_exp(orgulloso, 'Orgulloso_dawhst').
video_exp(paciencia, 'Paciencia_fzqrqz').
video_exp(reir, 'Reir_qo9p8f').
video_exp(respetar, 'Respetar_qvl2bl').
video_exp(sentimiento, 'Sentimiento_a0iw5p').
video_exp(sentir, 'Sentir_wxaci5').
video_exp(serio, 'Serio_wnshwi').
video_exp(solitario, 'Solitario_qeauk5').
video_exp(sonreir, 'Sonreir_e0chyy').
video_exp(sueno, 'Sueno_cychpo').
video_exp(sufrir, 'Sufrir_qgxffx').
video_exp(timido, 'Timido_vegqov').
video_exp(tranquilo, 'Tranquilo_fptyws').
video_exp(travieso, 'Travieso_kfn9xu').
video_exp(triste, 'Triste_y5gnoi').
video_exp(valiente, 'Valiente_vnhjsd').
video_exp(venganza, 'Venganza_swvk5l').
video_exp(verguenza, 'Verguenza_atofac').

% Regla
buscar_exp(Palabra, ID) :- video_exp(Palabra, ID).